CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	bitcoinJungleUsername TEXT UNIQUE,
	approved BOOLEAN NOT NULL DEFAULT FALSE,
	timestamp INT
);

CREATE TABLE payment_identifiers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	identifier TEXT UNIQUE
);

CREATE TABLE phone_numbers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	phoneNumber TEXT UNIQUE
);